# Generated by Django 5.1.1 on 2024-12-25 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='show_timings',
            field=models.JSONField(default=list),
        ),
    ]
