# Generated by Django 5.1.1 on 2024-12-25 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_alter_movie_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='image',
            field=models.ImageField(blank=True, default='movies/default.png', null=True, upload_to='movies/'),
        ),
    ]
