# Generated by Django 5.1.1 on 2024-12-25 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_alter_movie_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='image',
            field=models.ImageField(blank=True, default='https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRFusGlkNinqf4y11Ibzvi2o6bWMXVM5dHXiA&s', null=True, upload_to='movies/'),
        ),
    ]
